Drop database if exists aeroMoisselles;
-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 16:33:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aeroMoisselles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aeroMoisselles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aeroMoisselles` DEFAULT CHARACTER SET utf8 ;
USE `aeroMoisselles` ;

-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Avion` (
  `idAvion` INT NOT NULL AUTO_INCREMENT,
  `constructeur` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `unType` VARCHAR(45) NOT NULL,
  `nbplaces` INT NOT NULL,
  `unUsage` VARCHAR(80) NOT NULL,
  `moteur` VARCHAR(300) NOT NULL,
  `performances` VARCHAR(45) NOT NULL,
  `autonomie` VARCHAR(45) NOT NULL,
  `avionique` VARCHAR(500) NOT NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Voler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Voler` (
  `idVol` INT NOT NULL AUTO_INCREMENT,
  `zoneDepart` VARCHAR(300) NOT NULL,
  `zoneDestination` VARCHAR(300) NOT NULL,
  `circuit` VARCHAR(3000) NOT NULL,
  `dateHeureRDV` DATETIME NOT NULL,
  `dureeVol` VARCHAR(45) NOT NULL,
  `Avion_idAvion` INT NOT NULL,
  PRIMARY KEY (`idVol`, `Avion_idAvion`),
  INDEX `fk_Voler_Avion1_idx` (`Avion_idAvion` ASC),
  CONSTRAINT `fk_Voler_Avion1`
    FOREIGN KEY (`Avion_idAvion`)
    REFERENCES `aeroMoisselles`.`Avion` (`idAvion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Reservation` (
  `idReserver` INT NOT NULL AUTO_INCREMENT,
  `paye` INT(1) NULL,
  `Voler_idVol` INT NOT NULL,
  PRIMARY KEY (`idReserver`, `Voler_idVol`),
  INDEX `fk_Reservation_Voler1_idx` (`Voler_idVol` ASC),
  CONSTRAINT `fk_Reservation_Voler1`
    FOREIGN KEY (`Voler_idVol`)
    REFERENCES `aeroMoisselles`.`Voler` (`idVol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`TarifBapteme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`TarifBapteme` (
  `idTarifB` INT NOT NULL AUTO_INCREMENT,
  `typeAvion` VARCHAR(45) NOT NULL,
  `prix` DECIMAL(10) NOT NULL,
  `Reservation_idReserver` INT NOT NULL,
  `Reservation_Voler_idVol` INT NOT NULL,
  PRIMARY KEY (`idTarifB`, `Reservation_idReserver`, `Reservation_Voler_idVol`),
  INDEX `fk_TarifBapteme_Reservation1_idx` (`Reservation_idReserver` ASC, `Reservation_Voler_idVol` ASC),
  CONSTRAINT `fk_TarifBapteme_Reservation1`
    FOREIGN KEY (`Reservation_idReserver` , `Reservation_Voler_idVol`)
    REFERENCES `aeroMoisselles`.`Reservation` (`idReserver` , `Voler_idVol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Groupe` (
  `idGroupe` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Membre` (
  `idMembre` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(45) NOT NULL,
  `motPasse` VARCHAR(999) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `numTel` VARCHAR(14) NOT NULL,
  `adresse` VARCHAR(300) NOT NULL,
  `cp` INT(5) NOT NULL,
  `ville` VARCHAR(80) NOT NULL,
  `Groupe_idGroupe` INT NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `date_inscription` DATE NOT NULL,
  PRIMARY KEY (`idMembre`, `Groupe_idGroupe`),
  INDEX `fk_Membre_Groupe_idx` (`Groupe_idGroupe` ASC),
  CONSTRAINT `fk_Membre_Groupe`
    FOREIGN KEY (`Groupe_idGroupe`)
    REFERENCES `aeroMoisselles`.`Groupe` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`Passager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`Passager` (
  `idPassager` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NULL,
  `numTel` INT(10) NULL,
  `adresse` VARCHAR(300) NOT NULL,
  `cp` INT(5) NOT NULL,
  `ville` VARCHAR(80) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `Reservation_idReserver` INT NOT NULL,
  `Reservation_Voler_idVol` INT NOT NULL,
  PRIMARY KEY (`idPassager`, `Reservation_idReserver`, `Reservation_Voler_idVol`),
  INDEX `fk_Passager_Reservation1_idx` (`Reservation_idReserver` ASC, `Reservation_Voler_idVol` ASC),
  CONSTRAINT `fk_Passager_Reservation1`
    FOREIGN KEY (`Reservation_idReserver` , `Reservation_Voler_idVol`)
    REFERENCES `aeroMoisselles`.`Reservation` (`idReserver` , `Voler_idVol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeroMoisselles`.`veutRéserver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeroMoisselles`.`veutRéserver` (
  `idMembre` INT NOT NULL,
  `idGroupe` INT NOT NULL,
  `idReserver` INT NOT NULL,
  PRIMARY KEY (`idMembre`, `idGroupe`, `idReserver`),
  INDEX `fk_Membre_has_Reservation_Reservation1_idx` (`idReserver` ASC),
  INDEX `fk_Membre_has_Reservation_Membre1_idx` (`idMembre` ASC, `idGroupe` ASC),
  CONSTRAINT `fk_Membre_has_Reservation_Membre1`
    FOREIGN KEY (`idMembre` , `idGroupe`)
    REFERENCES `aeroMoisselles`.`Membre` (`idMembre` , `Groupe_idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membre_has_Reservation_Reservation1`
    FOREIGN KEY (`idReserver`)
    REFERENCES `aeroMoisselles`.`Reservation` (`idReserver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



insert into groupe (libelle) values ("administrateur");
insert into groupe (libelle) values ("utilisateur");
insert into groupe (libelle) values ("invite");
insert into groupe (libelle) values ("banni");

/*Ne pas effacer un groupe car ca risque de faire défaut sur le site*/

